# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

target 'EmployeeDirectoryApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeDirectoryApp
  pod 'SDWebImage'
end
